### ISSUE TITLE
Cargo sources are very out of date

### ISSUE THREAD

**Issue by tavurth** [rust-rethinkdb/reql#16]
[The cargo sources](https://crates.io/crates/rust-rethinkdb) are still at version 0.0.1, and fail to build on the nightly, giving Bufstream not found in std::io.

Could we update to 0.0.8?

**Comment by rushmorem** [comment]
That's a different crate. This crate is [reql](https://crates.io/crates/reql) on crates.io and it's already on `0.0.8`. I understand the confusion with this repos' organisation name though.

**Comment by tavurth** [comment]
Ok, thanks I didn't see it. Is there a way we could index reql when searching for rethinkdb on crates.io?

**Comment by rushmorem** [comment]
Unless I'm misunderstanding you, it already [shows up in the search results](https://crates.io/search?q=rethinkdb) for that term. It's on number 3. Just below `rust-rethinkdb`.

**Comment by tavurth** [comment]
Ah, my bad. I guess I got confused because the repo-group here has the same name as that crate.

**Comment by rushmorem** [comment]
No problem. I have renamed the organisation name to `rethinkdb-rs`. I hope this will help.
